my-apache:
  build: ./dockerfiles/apache
  volumes:
    - ./public:/var/www/html
  links:
    - mysql5:mysql5
    - mysql8:mysql8

mysql5:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

phpmyadmin5:
  image: nazarpc/phpmyadmin
  links:
    - mysql8:mysql

mysql8:
  image: mysql:8
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

phpmyadmin8:
  image: nazarpc/phpmyadmin
  links:
    - mysql8:mysql

